export const IL_ILCE_MAP: Record<string, { il: string; ilceler: Record<string, string> }> = {
  "adana": {
    il: "Adana",
    ilceler: {
      "aladag": "Aladağ",
      "ceyhan": "Ceyhan",
      "cukurova": "Çukurova",
      "feke": "Feke",
      "imamoglu": "İmamoğlu",
      "karaisali": "Karaisalı",
      "karatas": "Karataş",
      "kozan": "Kozan",
      "pozanti": "Pozantı",
      "saimbeyli": "Saimbeyli",
      "saricam": "Sarıçam",
      "seyhan": "Seyhan",
      "tufanbeyli": "Tufanbeyli",
      "yumurtalik": "Yumurtalık",
      "yuregir": "Yüreğir",
    },
  },
  "adiyaman": {
    il: "Adıyaman",
    ilceler: {
      "besni": "Besni",
      "celikhan": "Çelikhan",
      "gerger": "Gerger",
      "golbasi": "Gölbaşı",
      "kahta": "Kahta",
      "merkez": "Merkez",
      "samsat": "Samsat",
      "sincik": "Sincik",
      "tut": "Tut",
    },
  },
  "afyonkarahisar": {
    il: "Afyonkarahisar",
    ilceler: {
      "basmakci": "Başmakçı",
      "bayat": "Bayat",
      "bolvadin": "Bolvadin",
      "cay": "Çay",
      "cobanlar": "Çobanlar",
      "dazkiri": "Dazkırı",
      "dinar": "Dinar",
      "emirdag": "Emirdağ",
      "evciler": "Evciler",
      "hocalar": "Hocalar",
      "ihsaniye": "İhsaniye",
      "iscehisar": "İscehisar",
      "kiziloren": "Kızılören",
      "merkez": "Merkez",
      "sandikli": "Sandıklı",
      "sinanpasa": "Sinanpaşa",
      "sultandagi": "Sultandağı",
      "suhut": "Şuhut",
    },
  },
  "agri": {
    il: "Ağrı",
    ilceler: {
      "diyadin": "Diyadin",
      "dogubayazit": "Doğubayazıt",
      "eleskirt": "Eleşkirt",
      "hamur": "Hamur",
      "merkez": "Merkez",
      "patnos": "Patnos",
      "taslicay": "Taşlıçay",
      "tutak": "Tutak",
    },
  },
  "aksaray": {
    il: "Aksaray",
    ilceler: {
      "agacoren": "Ağaçören",
      "eskil": "Eskil",
      "gulagac": "Gülağaç",
      "guzelyurt": "Güzelyurt",
      "merkez": "Merkez",
      "ortakoy": "Ortaköy",
      "sariyahsi": "Sarıyahşi",
      "sultanhani": "Sultanhanı",
    },
  },
  "amasya": {
    il: "Amasya",
    ilceler: {
      "goynucek": "Göynücek",
      "gumushacikoy": "Gümüşhacıköy",
      "hamamozu": "Hamamözü",
      "merkez": "Merkez",
      "merzifon": "Merzifon",
      "suluova": "Suluova",
      "tasova": "Taşova",
    },
  },
  "ankara": {
    il: "Ankara",
    ilceler: {
      "akyurt": "Akyurt",
      "altindag": "Altındağ",
      "ayas": "Ayaş",
      "bala": "Bala",
      "beypazari": "Beypazarı",
      "camlidere": "Çamlıdere",
      "cankaya": "Çankaya",
      "cubuk": "Çubuk",
      "elmadag": "Elmadağ",
      "etimesgut": "Etimesgut",
      "evren": "Evren",
      "golbasi": "Gölbaşı",
      "gudul": "Güdül",
      "haymana": "Haymana",
      "kalecik": "Kalecik",
      "kahramankazan": "Kahramankazan",
      "kecioren": "Keçiören",
      "kizilcahamam": "Kızılcahamam",
      "mamak": "Mamak",
      "nallihan": "Nallıhan",
      "polatli": "Polatlı",
      "pursaklar": "Pursaklar",
      "sincan": "Sincan",
      "sereflikochisar": "Şereflikoçhisar",
      "yenimahalle": "Yenimahalle",
    },
  },
  "antalya": {
    il: "Antalya",
    ilceler: {
      "akseki": "Akseki",
      "aksu": "Aksu",
      "alanya": "Alanya",
      "demre": "Demre",
      "dosemealti": "Döşemealtı",
      "elmali": "Elmalı",
      "finike": "Finike",
      "gazipasa": "Gazipaşa",
      "gundogmus": "Gündoğmuş",
      "ibradi": "İbradı",
      "kas": "Kaş",
      "kemer": "Kemer",
      "kepez": "Kepez",
      "konyaalti": "Konyaaltı",
      "korkuteli": "Korkuteli",
      "kumluca": "Kumluca",
      "manavgat": "Manavgat",
      "muratpasa": "Muratpaşa",
      "serik": "Serik",
    },
  },
  "ardahan": {
    il: "Ardahan",
    ilceler: {
      "cildir": "Çıldır",
      "damal": "Damal",
      "gole": "Göle",
      "hanak": "Hanak",
      "merkez": "Merkez",
      "posof": "Posof",
    },
  },
  "artvin": {
    il: "Artvin",
    ilceler: {
      "ardanuc": "Ardanuç",
      "arhavi": "Arhavi",
      "borcka": "Borçka",
      "hopa": "Hopa",
      "kemalpasa": "Kemalpaşa",
      "merkez": "Merkez",
      "murgul": "Murgul",
      "savsat": "Şavşat",
      "yusufeli": "Yusufeli",
    },
  },
  "aydin": {
    il: "Aydın",
    ilceler: {
      "bozdogan": "Bozdoğan",
      "buharkent": "Buharkent",
      "cine": "Çine",
      "didim": "Didim",
      "efeler": "Efeler",
      "germencik": "Germencik",
      "incirliova": "İncirliova",
      "karacasu": "Karacasu",
      "karpuzlu": "Karpuzlu",
      "kocarli": "Koçarlı",
      "kosk": "Köşk",
      "kusadasi": "Kuşadası",
      "kuyucak": "Kuyucak",
      "nazilli": "Nazilli",
      "soke": "Söke",
      "sultanhisar": "Sultanhisar",
      "yenipazar": "Yenipazar",
    },
  },
  "balikesir": {
    il: "Balıkesir",
    ilceler: {
      "altieylul": "Altıeylül",
      "ayvalik": "Ayvalık",
      "balya": "Balya",
      "bandirma": "Bandırma",
      "bigadic": "Bigadiç",
      "burhaniye": "Burhaniye",
      "dursunbey": "Dursunbey",
      "edremit": "Edremit",
      "erdek": "Erdek",
      "gomec": "Gömeç",
      "gonen": "Gönen",
      "havran": "Havran",
      "ivrindi": "İvrindi",
      "karesi": "Karesi",
      "kepsut": "Kepsut",
      "manyas": "Manyas",
      "marmara": "Marmara",
      "savastepe": "Savaştepe",
      "sindirgi": "Sındırgı",
      "susurluk": "Susurluk",
    },
  },
  "bartin": {
    il: "Bartın",
    ilceler: {
      "amasra": "Amasra",
      "kurucasile": "Kurucaşile",
      "merkez": "Merkez",
      "ulus": "Ulus",
    },
  },
  "batman": {
    il: "Batman",
    ilceler: {
      "besiri": "Beşiri",
      "gercus": "Gercüş",
      "hasankeyf": "Hasankeyf",
      "kozluk": "Kozluk",
      "merkez": "Merkez",
      "sason": "Sason",
    },
  },
  "bayburt": {
    il: "Bayburt",
    ilceler: {
      "aydintepe": "Aydıntepe",
      "demirozu": "Demirözü",
      "merkez": "Merkez",
    },
  },
  "bilecik": {
    il: "Bilecik",
    ilceler: {
      "bozuyuk": "Bozüyük",
      "golpazari": "Gölpazarı",
      "inhisar": "İnhisar",
      "merkez": "Merkez",
      "osmaneli": "Osmaneli",
      "pazaryeri": "Pazaryeri",
      "sogut": "Söğüt",
      "yenipazar": "Yenipazar",
    },
  },
  "bingol": {
    il: "Bingöl",
    ilceler: {
      "adakli": "Adaklı",
      "genc": "Genç",
      "karliova": "Karlıova",
      "kigi": "Kiğı",
      "merkez": "Merkez",
      "solhan": "Solhan",
      "yayladere": "Yayladere",
      "yedisu": "Yedisu",
    },
  },
  "bitlis": {
    il: "Bitlis",
    ilceler: {
      "adilcevaz": "Adilcevaz",
      "ahlat": "Ahlat",
      "guroymak": "Güroymak",
      "hizan": "Hizan",
      "merkez": "Merkez",
      "mutki": "Mutki",
      "tatvan": "Tatvan",
    },
  },
  "bolu": {
    il: "Bolu",
    ilceler: {
      "dortdivan": "Dörtdivan",
      "gerede": "Gerede",
      "goynuk": "Göynük",
      "kibriscik": "Kıbrıscık",
      "mengen": "Mengen",
      "merkez": "Merkez",
      "mudurnu": "Mudurnu",
      "seben": "Seben",
      "yenicaga": "Yeniçağa",
    },
  },
  "burdur": {
    il: "Burdur",
    ilceler: {
      "aglasun": "Ağlasun",
      "altinyayla": "Altınyayla",
      "bucak": "Bucak",
      "cavdir": "Çavdır",
      "celtikci": "Çeltikçi",
      "golhisar": "Gölhisar",
      "karamanli": "Karamanlı",
      "kemer": "Kemer",
      "merkez": "Merkez",
      "tefenni": "Tefenni",
      "yesilova": "Yeşilova",
    },
  },
  "bursa": {
    il: "Bursa",
    ilceler: {
      "buyukorhan": "Büyükorhan",
      "gemlik": "Gemlik",
      "gursu": "Gürsu",
      "harmancik": "Harmancık",
      "inegol": "İnegöl",
      "iznik": "İznik",
      "karacabey": "Karacabey",
      "keles": "Keles",
      "kestel": "Kestel",
      "mudanya": "Mudanya",
      "mustafakemalpasa": "Mustafakemalpaşa",
      "nilufer": "Nilüfer",
      "orhaneli": "Orhaneli",
      "orhangazi": "Orhangazi",
      "osmangazi": "Osmangazi",
      "yenisehir": "Yenişehir",
      "yildirim": "Yıldırım",
    },
  },
  "canakkale": {
    il: "Çanakkale",
    ilceler: {
      "ayvacik": "Ayvacık",
      "bayramic": "Bayramiç",
      "biga": "Biga",
      "bozcaada": "Bozcaada",
      "can": "Çan",
      "eceabat": "Eceabat",
      "ezine": "Ezine",
      "gelibolu": "Gelibolu",
      "gokceada": "Gökçeada",
      "lapseki": "Lapseki",
      "merkez": "Merkez",
      "yenice": "Yenice",
    },
  },
  "cankiri": {
    il: "Çankırı",
    ilceler: {
      "atkaracalar": "Atkaracalar",
      "bayramoren": "Bayramören",
      "cerkes": "Çerkeş",
      "eldivan": "Eldivan",
      "ilgaz": "Ilgaz",
      "kizilirmak": "Kızılırmak",
      "korgun": "Korgun",
      "kursunlu": "Kurşunlu",
      "merkez": "Merkez",
      "orta": "Orta",
      "sabanozu": "Şabanözü",
      "yaprakli": "Yapraklı",
    },
  },
  "corum": {
    il: "Çorum",
    ilceler: {
      "alaca": "Alaca",
      "bayat": "Bayat",
      "bogazkale": "Boğazkale",
      "dodurga": "Dodurga",
      "iskilip": "İskilip",
      "kargi": "Kargı",
      "lacin": "Laçin",
      "mecitozu": "Mecitözü",
      "merkez": "Merkez",
      "oguzlar": "Oğuzlar",
      "ortakoy": "Ortaköy",
      "osmancik": "Osmancık",
      "sungurlu": "Sungurlu",
      "ugurludag": "Uğurludağ",
    },
  },
  "denizli": {
    il: "Denizli",
    ilceler: {
      "acipayam": "Acıpayam",
      "babadag": "Babadağ",
      "baklan": "Baklan",
      "bekilli": "Bekilli",
      "beyagac": "Beyağaç",
      "bozkurt": "Bozkurt",
      "buldan": "Buldan",
      "cal": "Çal",
      "cameli": "Çameli",
      "cardak": "Çardak",
      "civril": "Çivril",
      "guney": "Güney",
      "honaz": "Honaz",
      "kale": "Kale",
      "merkezefendi": "Merkezefendi",
      "pamukkale": "Pamukkale",
      "saraykoy": "Sarayköy",
      "serinhisar": "Serinhisar",
      "tavas": "Tavas",
    },
  },
  "diyarbakir": {
    il: "Diyarbakır",
    ilceler: {
      "baglar": "Bağlar",
      "bismil": "Bismil",
      "cermik": "Çermik",
      "cinar": "Çınar",
      "cungus": "Çüngüş",
      "dicle": "Dicle",
      "egil": "Eğil",
      "ergani": "Ergani",
      "hani": "Hani",
      "hazro": "Hazro",
      "kayapinar": "Kayapınar",
      "kocakoy": "Kocaköy",
      "kulp": "Kulp",
      "lice": "Lice",
      "silvan": "Silvan",
      "sur": "Sur",
      "yenisehir": "Yenişehir",
    },
  },
  "duzce": {
    il: "Düzce",
    ilceler: {
      "akcakoca": "Akçakoca",
      "cumayeri": "Cumayeri",
      "cilimli": "Çilimli",
      "golyaka": "Gölyaka",
      "gumusova": "Gümüşova",
      "kaynasli": "Kaynaşlı",
      "merkez": "Merkez",
      "yigilca": "Yığılca",
    },
  },
  "edirne": {
    il: "Edirne",
    ilceler: {
      "enez": "Enez",
      "havsa": "Havsa",
      "ipsala": "İpsala",
      "kesan": "Keşan",
      "lalapasa": "Lalapaşa",
      "meric": "Meriç",
      "merkez": "Merkez",
      "suloglu": "Süloğlu",
      "uzunkopru": "Uzunköprü",
    },
  },
  "elazig": {
    il: "Elazığ",
    ilceler: {
      "agin": "Ağın",
      "alacakaya": "Alacakaya",
      "aricak": "Arıcak",
      "baskil": "Baskil",
      "karakocan": "Karakoçan",
      "keban": "Keban",
      "kovancilar": "Kovancılar",
      "maden": "Maden",
      "merkez": "Merkez",
      "palu": "Palu",
      "sivrice": "Sivrice",
    },
  },
  "erzincan": {
    il: "Erzincan",
    ilceler: {
      "cayirli": "Çayırlı",
      "ilic": "İliç",
      "kemah": "Kemah",
      "kemaliye": "Kemaliye",
      "merkez": "Merkez",
      "otlukbeli": "Otlukbeli",
      "refahiye": "Refahiye",
      "tercan": "Tercan",
      "uzumlu": "Üzümlü",
    },
  },
  "erzurum": {
    il: "Erzurum",
    ilceler: {
      "askale": "Aşkale",
      "aziziye": "Aziziye",
      "cat": "Çat",
      "hinis": "Hınıs",
      "horasan": "Horasan",
      "ispir": "İspir",
      "karacoban": "Karaçoban",
      "karayazi": "Karayazı",
      "koprukoy": "Köprüköy",
      "merkez": "Merkez",
      "narman": "Narman",
      "oltu": "Oltu",
      "olur": "Olur",
      "palandoken": "Palandöken",
      "pasinler": "Pasinler",
      "pazaryolu": "Pazaryolu",
      "senkaya": "Şenkaya",
      "tekman": "Tekman",
      "tortum": "Tortum",
      "uzundere": "Uzundere",
      "yakutiye": "Yakutiye",
    },
  },
  "eskisehir": {
    il: "Eskişehir",
    ilceler: {
      "alpu": "Alpu",
      "beylikova": "Beylikova",
      "cifteler": "Çifteler",
      "gunyuzu": "Günyüzü",
      "han": "Han",
      "inonu": "İnönü",
      "mahmudiye": "Mahmudiye",
      "mihalgazi": "Mihalgazi",
      "mihaliccik": "Mihalıççık",
      "odunpazari": "Odunpazarı",
      "saricakaya": "Sarıcakaya",
      "seyitgazi": "Seyitgazi",
      "sivrihisar": "Sivrihisar",
      "tepebasi": "Tepebaşı",
    },
  },
  "gaziantep": {
    il: "Gaziantep",
    ilceler: {
      "araban": "Araban",
      "islahiye": "İslahiye",
      "karkamis": "Karkamış",
      "nizip": "Nizip",
      "nurdagi": "Nurdağı",
      "oguzeli": "Oğuzeli",
      "sahinbey": "Şahinbey",
      "sehitkamil": "Şehitkamil",
      "yavuzeli": "Yavuzeli",
    },
  },
  "giresun": {
    il: "Giresun",
    ilceler: {
      "alucra": "Alucra",
      "bulancak": "Bulancak",
      "camoluk": "Çamoluk",
      "canakci": "Çanakçı",
      "dereli": "Dereli",
      "dogankent": "Doğankent",
      "espiye": "Espiye",
      "eynesil": "Eynesil",
      "gorele": "Görele",
      "guce": "Güce",
      "kesap": "Keşap",
      "merkez": "Merkez",
      "piraziz": "Piraziz",
      "sebinkarahisar": "Şebinkarahisar",
      "tirebolu": "Tirebolu",
      "yaglidere": "Yağlıdere",
    },
  },
  "gumushane": {
    il: "Gümüşhane",
    ilceler: {
      "kelkit": "Kelkit",
      "kose": "Köse",
      "kurtun": "Kürtün",
      "merkez": "Merkez",
      "siran": "Şiran",
      "torul": "Torul",
    },
  },
  "hakkari": {
    il: "Hakkari",
    ilceler: {
      "cukurca": "Çukurca",
      "derecik": "Derecik",
      "merkez": "Merkez",
      "semdinli": "Şemdinli",
      "yuksekova": "Yüksekova",
    },
  },
  "hatay": {
    il: "Hatay",
    ilceler: {
      "altinozu": "Altınözü",
      "antakya": "Antakya",
      "arsuz": "Arsuz",
      "belen": "Belen",
      "defne": "Defne",
      "dortyol": "Dörtyol",
      "erzin": "Erzin",
      "hassa": "Hassa",
      "iskenderun": "İskenderun",
      "kirikhan": "Kırıkhan",
      "kumlu": "Kumlu",
      "mandaci": "Mandacı",
      "payas": "Payas",
      "reyhanli": "Reyhanlı",
      "samandag": "Samandağ",
      "serinyol": "Serinyol",
      "yayladagi": "Yayladağı",
    },
  },
  "igdir": {
    il: "Iğdır",
    ilceler: {
      "aralik": "Aralık",
      "karakoyunlu": "Karakoyunlu",
      "merkez": "Merkez",
      "tuzluca": "Tuzluca",
    },
  },
  "isparta": {
    il: "Isparta",
    ilceler: {
      "aksu": "Aksu",
      "atabey": "Atabey",
      "egirdir": "Eğirdir",
      "gelendost": "Gelendost",
      "gonen": "Gönen",
      "keciborlu": "Keçiborlu",
      "merkez": "Merkez",
      "senirkent": "Senirkent",
      "sutculer": "Sütçüler",
      "sarkikaraagac": "Şarkikaraağaç",
      "uluborlu": "Uluborlu",
      "yalvac": "Yalvaç",
      "yenisarbademli": "Yenişarbademli",
    },
  },
  "istanbul": {
    il: "İstanbul",
    ilceler: {
      "adalar": "Adalar",
      "arnavutkoy": "Arnavutköy",
      "atasehir": "Ataşehir",
      "avcilar": "Avcılar",
      "bagcilar": "Bağcılar",
      "bahcelievler": "Bahçelievler",
      "bakirkoy": "Bakırköy",
      "basaksehir": "Başakşehir",
      "bayrampasa": "Bayrampaşa",
      "besiktas": "Beşiktaş",
      "beykoz": "Beykoz",
      "beylikduzu": "Beylikdüzü",
      "beyoglu": "Beyoğlu",
      "buyukcekmece": "Büyükçekmece",
      "catalca": "Çatalca",
      "cekmekoy": "Çekmeköy",
      "esenler": "Esenler",
      "esenyurt": "Esenyurt",
      "eyupsultan": "Eyüpsultan",
      "fatih": "Fatih",
      "gaziosmanpasa": "Gaziosmanpaşa",
      "gungoren": "Güngören",
      "kadikoy": "Kadıköy",
      "kagithane": "Kağıthane",
      "kartal": "Kartal",
      "kucukcekmece": "Küçükçekmece",
      "maltepe": "Maltepe",
      "pendik": "Pendik",
      "sancaktepe": "Sancaktepe",
      "sariyer": "Sarıyer",
      "silivri": "Silivri",
      "sultanbeyli": "Sultanbeyli",
      "sultangazi": "Sultangazi",
      "sile": "Şile",
      "sisli": "Şişli",
      "tuzla": "Tuzla",
      "umraniye": "Ümraniye",
      "uskudar": "Üsküdar",
      "zeytinburnu": "Zeytinburnu",
    },
  },
  "izmir": {
    il: "İzmir",
    ilceler: {
      "aliaga": "Aliağa",
      "balcova": "Balçova",
      "bayindir": "Bayındır",
      "bayrakli": "Bayraklı",
      "bergama": "Bergama",
      "beydag": "Beydağ",
      "bornova": "Bornova",
      "buca": "Buca",
      "cesme": "Çeşme",
      "cigli": "Çiğli",
      "dikili": "Dikili",
      "foca": "Foça",
      "gaziemir": "Gaziemir",
      "guzelbahce": "Güzelbahçe",
      "karabaglar": "Karabağlar",
      "karaburun": "Karaburun",
      "karsiyaka": "Karşıyaka",
      "kemalpasa": "Kemalpaşa",
      "kinik": "Kınık",
      "kiraz": "Kiraz",
      "konak": "Konak",
      "menderes": "Menderes",
      "menemen": "Menemen",
      "narlidere": "Narlıdere",
      "odemis": "Ödemiş",
      "seferihisar": "Seferihisar",
      "selcuk": "Selçuk",
      "tire": "Tire",
      "torbali": "Torbalı",
      "urla": "Urla",
    },
  },
  "kahramanmaras": {
    il: "Kahramanmaraş",
    ilceler: {
      "afsin": "Afşin",
      "andirin": "Andırın",
      "caglayancerit": "Çağlayancerit",
      "dulkadiroglu": "Dulkadiroğlu",
      "ekinozu": "Ekinözü",
      "elbistan": "Elbistan",
      "goksun": "Göksun",
      "merkez": "Merkez",
      "nurhak": "Nurhak",
      "onikisubat": "Onikişubat",
      "pazarcik": "Pazarcık",
      "turkoglu": "Türkoğlu",
    },
  },
  "karabuk": {
    il: "Karabük",
    ilceler: {
      "eflani": "Eflani",
      "eskipazar": "Eskipazar",
      "merkez": "Merkez",
      "ovacik": "Ovacık",
      "safranbolu": "Safranbolu",
      "yenice": "Yenice",
    },
  },
  "karaman": {
    il: "Karaman",
    ilceler: {
      "ayranci": "Ayrancı",
      "basyayla": "Başyayla",
      "ermenek": "Ermenek",
      "kazimkarabekir": "Kazımkarabekir",
      "merkez": "Merkez",
      "sariveliler": "Sarıveliler",
    },
  },
  "kars": {
    il: "Kars",
    ilceler: {
      "akyaka": "Akyaka",
      "arpacay": "Arpaçay",
      "digor": "Digor",
      "kagizman": "Kağızman",
      "merkez": "Merkez",
      "sarikamis": "Sarıkamış",
      "selim": "Selim",
      "susuz": "Susuz",
    },
  },
  "kastamonu": {
    il: "Kastamonu",
    ilceler: {
      "abana": "Abana",
      "agli": "Ağlı",
      "arac": "Araç",
      "azdavay": "Azdavay",
      "bozkurt": "Bozkurt",
      "cide": "Cide",
      "catalzeytin": "Çatalzeytin",
      "daday": "Daday",
      "devrekani": "Devrekani",
      "doganyurt": "Doğanyurt",
      "hanonu": "Hanönü",
      "ihsangazi": "İhsangazi",
      "inebolu": "İnebolu",
      "kure": "Küre",
      "merkez": "Merkez",
      "pinarbasi": "Pınarbaşı",
      "seydiler": "Seydiler",
      "senpazar": "Şenpazar",
      "taskopru": "Taşköprü",
      "tosya": "Tosya",
    },
  },
  "kayseri": {
    il: "Kayseri",
    ilceler: {
      "akkisla": "Akkışla",
      "bunyan": "Bünyan",
      "develi": "Develi",
      "felahiye": "Felahiye",
      "hacilar": "Hacılar",
      "incesu": "İncesu",
      "kocasinan": "Kocasinan",
      "melikgazi": "Melikgazi",
      "ozvatan": "Özvatan",
      "pinarbasi": "Pınarbaşı",
      "sarioglan": "Sarıoğlan",
      "sariz": "Sarız",
      "talas": "Talas",
      "tomarza": "Tomarza",
      "yahyali": "Yahyalı",
      "yesilhisar": "Yeşilhisar",
    },
  },
  "kirikkale": {
    il: "Kırıkkale",
    ilceler: {
      "bahsili": "Bahşili",
      "baliseyh": "Balışeyh",
      "celebi": "Çelebi",
      "delice": "Delice",
      "karakecili": "Karakeçili",
      "keskin": "Keskin",
      "merkez": "Merkez",
      "sulakyurt": "Sulakyurt",
      "yahsihan": "Yahşihan",
    },
  },
  "kirklareli": {
    il: "Kırklareli",
    ilceler: {
      "babaeski": "Babaeski",
      "demirkoy": "Demirköy",
      "kofcaz": "Kofçaz",
      "luleburgaz": "Lüleburgaz",
      "merkez": "Merkez",
      "pehlivankoy": "Pehlivanköy",
      "pinarhisar": "Pınarhisar",
      "vize": "Vize",
    },
  },
  "kirsehir": {
    il: "Kırşehir",
    ilceler: {
      "akcakent": "Akçakent",
      "akpinar": "Akpınar",
      "boztepe": "Boztepe",
      "cicekdagi": "Çiçekdağı",
      "kaman": "Kaman",
      "merkez": "Merkez",
      "mucur": "Mucur",
    },
  },
  "kilis": {
    il: "Kilis",
    ilceler: {
      "elbeyli": "Elbeyli",
      "merkez": "Merkez",
      "musabeyli": "Musabeyli",
      "polateli": "Polateli",
    },
  },
  "kocaeli": {
    il: "Kocaeli",
    ilceler: {
      "basiskele": "Başiskele",
      "cayirova": "Çayırova",
      "darica": "Darıca",
      "derince": "Derince",
      "dilovasi": "Dilovası",
      "gebze": "Gebze",
      "golcuk": "Gölcük",
      "izmit": "İzmit",
      "kandira": "Kandıra",
      "karamursel": "Karamürsel",
      "kartepe": "Kartepe",
      "korfez": "Körfez",
    },
  },
  "konya": {
    il: "Konya",
    ilceler: {
      "ahirli": "Ahırlı",
      "akoren": "Akören",
      "aksehir": "Akşehir",
      "altinekin": "Altınekin",
      "beysehir": "Beyşehir",
      "bozkir": "Bozkır",
      "cihanbeyli": "Cihanbeyli",
      "celtik": "Çeltik",
      "cumra": "Çumra",
      "derbent": "Derbent",
      "derebucak": "Derebucak",
      "doganhisar": "Doğanhisar",
      "emirgazi": "Emirgazi",
      "eregli": "Ereğli",
      "guneysinir": "Güneysınır",
      "hadim": "Hadim",
      "halkapinar": "Halkapınar",
      "huyuk": "Hüyük",
      "ilgin": "Ilgın",
      "kadinhani": "Kadınhanı",
      "karapinar": "Karapınar",
      "karatay": "Karatay",
      "kulu": "Kulu",
      "meram": "Meram",
      "sarayonu": "Sarayönü",
      "selcuklu": "Selçuklu",
      "seydisehir": "Seydişehir",
      "taskent": "Taşkent",
      "tuzlukcu": "Tuzlukçu",
      "yalihuyuk": "Yalıhüyük",
      "yunak": "Yunak",
    },
  },
  "kutahya": {
    il: "Kütahya",
    ilceler: {
      "altintas": "Altıntaş",
      "aslanapa": "Aslanapa",
      "cavdarhisar": "Çavdarhisar",
      "domanic": "Domaniç",
      "dumlupinar": "Dumlupınar",
      "emet": "Emet",
      "gediz": "Gediz",
      "hisarcik": "Hisarcık",
      "merkez": "Merkez",
      "pazarlar": "Pazarlar",
      "simav": "Simav",
      "saphane": "Şaphane",
      "tavsanli": "Tavşanlı",
    },
  },
  "malatya": {
    il: "Malatya",
    ilceler: {
      "akcadag": "Akçadağ",
      "arapgir": "Arapgir",
      "arguvan": "Arguvan",
      "battalgazi": "Battalgazi",
      "darende": "Darende",
      "dogansehir": "Doğanşehir",
      "doganyol": "Doğanyol",
      "hekimhan": "Hekimhan",
      "kale": "Kale",
      "kuluncak": "Kuluncak",
      "merkez": "Merkez",
      "puturge": "Pütürge",
      "yazihan": "Yazıhan",
      "yesilyurt": "Yeşilyurt",
    },
  },
  "manisa": {
    il: "Manisa",
    ilceler: {
      "ahmetli": "Ahmetli",
      "akhisar": "Akhisar",
      "alasehir": "Alaşehir",
      "demirci": "Demirci",
      "golmarmara": "Gölmarmara",
      "gordes": "Gördes",
      "kirkagac": "Kırkağaç",
      "koprubasi": "Köprübaşı",
      "kula": "Kula",
      "merkez": "Merkez",
      "salihli": "Salihli",
      "sarigol": "Sarıgöl",
      "saruhanli": "Saruhanlı",
      "selendi": "Selendi",
      "soma": "Soma",
      "sehzadeler": "Şehzadeler",
      "turgutlu": "Turgutlu",
      "yunusemre": "Yunusemre",
    },
  },
  "mardin": {
    il: "Mardin",
    ilceler: {
      "artuklu": "Artuklu",
      "dargecit": "Dargeçit",
      "derik": "Derik",
      "kiziltepe": "Kızıltepe",
      "mazidagi": "Mazıdağı",
      "merkez": "Merkez",
      "midyat": "Midyat",
      "nusaybin": "Nusaybin",
      "omerli": "Ömerli",
      "savur": "Savur",
      "yesilli": "Yeşilli",
    },
  },
  "mersin": {
    il: "Mersin",
    ilceler: {
      "akdeniz": "Akdeniz",
      "anamur": "Anamur",
      "aydincik": "Aydıncık",
      "bozyazi": "Bozyazı",
      "camliyayla": "Çamlıyayla",
      "erdemli": "Erdemli",
      "gulnar": "Gülnar",
      "mezitli": "Mezitli",
      "mut": "Mut",
      "silifke": "Silifke",
      "tarsus": "Tarsus",
      "toroslar": "Toroslar",
      "yenisehir": "Yenişehir",
    },
  },
  "mugla": {
    il: "Muğla",
    ilceler: {
      "bodrum": "Bodrum",
      "dalaman": "Dalaman",
      "datca": "Datça",
      "fethiye": "Fethiye",
      "kavaklidere": "Kavaklıdere",
      "koycegiz": "Köyceğiz",
      "marmaris": "Marmaris",
      "mentese": "Menteşe",
      "milas": "Milas",
      "ortaca": "Ortaca",
      "seydikemer": "Seydikemer",
      "ula": "Ula",
      "yatagan": "Yatağan",
    },
  },
  "mus": {
    il: "Muş",
    ilceler: {
      "bulanik": "Bulanık",
      "haskoy": "Hasköy",
      "korkut": "Korkut",
      "malazgirt": "Malazgirt",
      "merkez": "Merkez",
      "varto": "Varto",
    },
  },
  "nevsehir": {
    il: "Nevşehir",
    ilceler: {
      "acigol": "Acıgöl",
      "avanos": "Avanos",
      "derinkuyu": "Derinkuyu",
      "gulsehir": "Gülşehir",
      "hacibektas": "Hacıbektaş",
      "kozakli": "Kozaklı",
      "merkez": "Merkez",
      "urgup": "Ürgüp",
    },
  },
  "nigde": {
    il: "Niğde",
    ilceler: {
      "altunhisar": "Altunhisar",
      "bor": "Bor",
      "camardi": "Çamardı",
      "ciftlik": "Çiftlik",
      "merkez": "Merkez",
      "ulukisla": "Ulukışla",
    },
  },
  "ordu": {
    il: "Ordu",
    ilceler: {
      "akkus": "Akkuş",
      "altinordu": "Altınordu",
      "aybasti": "Aybastı",
      "camas": "Çamaş",
      "catalpinar": "Çatalpınar",
      "caybasi": "Çaybaşı",
      "fatsa": "Fatsa",
      "golkoy": "Gölköy",
      "gulyali": "Gülyalı",
      "gurgentepe": "Gürgentepe",
      "ikizce": "İkizce",
      "kabaduz": "Kabadüz",
      "kabatas": "Kabataş",
      "korgan": "Korgan",
      "kumru": "Kumru",
      "mesudiye": "Mesudiye",
      "persembe": "Perşembe",
      "ulubey": "Ulubey",
      "unye": "Ünye",
    },
  },
  "osmaniye": {
    il: "Osmaniye",
    ilceler: {
      "bahce": "Bahçe",
      "duzici": "Düziçi",
      "hasanbeyli": "Hasanbeyli",
      "kadirli": "Kadirli",
      "merkez": "Merkez",
      "sumbas": "Sumbas",
      "toprakkale": "Toprakkale",
    },
  },
  "rize": {
    il: "Rize",
    ilceler: {
      "ardesen": "Ardeşen",
      "camlihemsin": "Çamlıhemşin",
      "cayeli": "Çayeli",
      "derepazari": "Derepazarı",
      "findikli": "Fındıklı",
      "guneysu": "Güneysu",
      "hemsin": "Hemşin",
      "ikizdere": "İkizdere",
      "iyidere": "İyidere",
      "kalkandere": "Kalkandere",
      "merkez": "Merkez",
      "pazar": "Pazar",
    },
  },
  "sakarya": {
    il: "Sakarya",
    ilceler: {
      "adapazari": "Adapazarı",
      "akyazi": "Akyazı",
      "arifiye": "Arifiye",
      "erenler": "Erenler",
      "ferizli": "Ferizli",
      "geyve": "Geyve",
      "hendek": "Hendek",
      "karapurcek": "Karapürçek",
      "karasu": "Karasu",
      "kaynarca": "Kaynarca",
      "kocaali": "Kocaali",
      "mithatpasa": "Mithatpaşa",
      "pamukova": "Pamukova",
      "sapanca": "Sapanca",
      "serdivan": "Serdivan",
      "sogutlu": "Söğütlü",
      "tarakli": "Taraklı",
    },
  },
  "samsun": {
    il: "Samsun",
    ilceler: {
      "alacam": "Alaçam",
      "asarcik": "Asarcık",
      "atakum": "Atakum",
      "ayvacik": "Ayvacık",
      "bafra": "Bafra",
      "canik": "Canik",
      "carsamba": "Çarşamba",
      "havza": "Havza",
      "ilkadim": "İlkadım",
      "kavak": "Kavak",
      "ladik": "Ladik",
      "salipazari": "Salıpazarı",
      "tekkekoy": "Tekkeköy",
      "terme": "Terme",
      "vezirkopru": "Vezirköprü",
      "yakakent": "Yakakent",
    },
  },
  "siirt": {
    il: "Siirt",
    ilceler: {
      "baykan": "Baykan",
      "eruh": "Eruh",
      "kurtalan": "Kurtalan",
      "merkez": "Merkez",
      "pervari": "Pervari",
      "sirvan": "Şirvan",
      "tillo": "Tillo",
    },
  },
  "sinop": {
    il: "Sinop",
    ilceler: {
      "ayancik": "Ayancık",
      "boyabat": "Boyabat",
      "dikmen": "Dikmen",
      "duragan": "Durağan",
      "erfelek": "Erfelek",
      "gerze": "Gerze",
      "merkez": "Merkez",
      "sarayduzu": "Saraydüzü",
      "turkeli": "Türkeli",
    },
  },
  "sivas": {
    il: "Sivas",
    ilceler: {
      "akincilar": "Akıncılar",
      "altinyayla": "Altınyayla",
      "divrigi": "Divriği",
      "dogansar": "Doğanşar",
      "gemerek": "Gemerek",
      "golova": "Gölova",
      "gurun": "Gürun",
      "hafik": "Hafik",
      "imranli": "İmranlı",
      "kangal": "Kangal",
      "koyulhisar": "Koyulhisar",
      "merkez": "Merkez",
      "susehri": "Suşehri",
      "sarkisla": "Şarkışla",
      "ulas": "Ulaş",
      "yildizeli": "Yıldızeli",
      "zara": "Zara",
    },
  },
  "sanliurfa": {
    il: "Şanlıurfa",
    ilceler: {
      "akcakale": "Akçakale",
      "birecik": "Birecik",
      "bozova": "Bozova",
      "ceylanpinar": "Ceylanpınar",
      "eyyubiye": "Eyyübiye",
      "halfeti": "Halfeti",
      "haliliye": "Haliliye",
      "harran": "Harran",
      "hilvan": "Hilvan",
      "karakopru": "Karaköprü",
      "merkez": "Merkez",
      "siverek": "Siverek",
      "suruc": "Suruç",
      "viransehir": "Viranşehir",
    },
  },
  "sirnak": {
    il: "Şırnak",
    ilceler: {
      "beytussebap": "Beytüşşebap",
      "cizre": "Cizre",
      "guclukonak": "Güçlükonak",
      "idil": "İdil",
      "merkez": "Merkez",
      "silopi": "Silopi",
      "uludere": "Uludere",
    },
  },
  "tekirdag": {
    il: "Tekirdağ",
    ilceler: {
      "cerkezkoy": "Çerkezköy",
      "corlu": "Çorlu",
      "ergene": "Ergene",
      "hayrabolu": "Hayrabolu",
      "kapakli": "Kapaklı",
      "malkara": "Malkara",
      "marmaraereglisi": "Marmaraereğlisi",
      "merkez": "Merkez",
      "muratli": "Muratlı",
      "saray": "Saray",
      "suleymanpasa": "Süleymanpaşa",
      "sarkoy": "Şarköy",
    },
  },
  "tokat": {
    il: "Tokat",
    ilceler: {
      "almus": "Almus",
      "artova": "Artova",
      "basciftlik": "Başçiftlik",
      "erbaa": "Erbaa",
      "merkez": "Merkez",
      "niksar": "Niksar",
      "pazar": "Pazar",
      "resadiye": "Reşadiye",
      "sulusaray": "Sulusaray",
      "turhal": "Turhal",
      "yesilyurt": "Yeşilyurt",
      "zile": "Zile",
    },
  },
  "trabzon": {
    il: "Trabzon",
    ilceler: {
      "akcaabat": "Akçaabat",
      "arakli": "Araklı",
      "arsin": "Arsin",
      "besikduzu": "Beşikdüzü",
      "carsibasi": "Çarşıbaşı",
      "caykara": "Çaykara",
      "dernekpazari": "Dernekpazarı",
      "duzkoy": "Düzköy",
      "hayrat": "Hayrat",
      "koprubasi": "Köprübaşı",
      "macka": "Maçka",
      "of": "Of",
      "ortahisar": "Ortahisar",
      "salpazari": "Şalpazarı",
      "surmene": "Sürmene",
      "tonya": "Tonya",
      "vakfikebir": "Vakfıkebir",
      "yomra": "Yomra",
    },
  },
  "tunceli": {
    il: "Tunceli",
    ilceler: {
      "cemisgezek": "Çemişgezek",
      "hozat": "Hozat",
      "mazgirt": "Mazgirt",
      "merkez": "Merkez",
      "nazimiye": "Nazımiye",
      "ovacik": "Ovacık",
      "pertek": "Pertek",
      "pulumur": "Pülümür",
    },
  },
  "usak": {
    il: "Uşak",
    ilceler: {
      "banaz": "Banaz",
      "esme": "Eşme",
      "karahalli": "Karahallı",
      "merkez": "Merkez",
      "sivasli": "Sivaslı",
      "ulubey": "Ulubey",
    },
  },
  "van": {
    il: "Van",
    ilceler: {
      "bahcesaray": "Bahçesaray",
      "baskale": "Başkale",
      "caldiran": "Çaldıran",
      "catak": "Çatak",
      "edremit": "Edremit",
      "ercis": "Erciş",
      "gevas": "Gevaş",
      "gurpinar": "Gürpınar",
      "ipekyolu": "İpekyolu",
      "merkez": "Merkez",
      "muradiye": "Muradiye",
      "ozalp": "Özalp",
      "saray": "Saray",
      "tusba": "Tuşba",
    },
  },
  "yalova": {
    il: "Yalova",
    ilceler: {
      "altinova": "Altınova",
      "armutlu": "Armutlu",
      "cinarcik": "Çınarcık",
      "ciftlikkoy": "Çiftlikköy",
      "merkez": "Merkez",
      "termal": "Termal",
    },
  },
  "yozgat": {
    il: "Yozgat",
    ilceler: {
      "akdagmadeni": "Akdağmadeni",
      "aydincik": "Aydıncık",
      "bogazliyan": "Boğazlıyan",
      "candir": "Çandır",
      "cayiralan": "Çayıralan",
      "cekerek": "Çekerek",
      "kadisehri": "Kadışehri",
      "merkez": "Merkez",
      "saraykent": "Saraykent",
      "sarikaya": "Sarıkaya",
      "sefaatli": "Şefaatli",
      "sorgun": "Sorgun",
      "yenifakili": "Yenifakılı",
      "yerkoy": "Yerköy",
    },
  },
  "zonguldak": {
    il: "Zonguldak",
    ilceler: {
      "alapli": "Alaplı",
      "caycuma": "Çaycuma",
      "devrek": "Devrek",
      "eregli": "Ereğli",
      "gokcebey": "Gökçebey",
      "kilimli": "Kilimli",
      "kozlu": "Kozlu",
      "merkez": "Merkez",
    },
  },
}