export const KATEGORI_MAP: Record<string, { name: string; parentId: string | null }> = {
  "alisveris": { name: "Alışveriş", parentId: null },
  "apart-kiralik": { name: "Apart & Kiralık", parentId: "cmm1c5s4n000f10huk1igr6a6" },
  "oto-kiralama": { name: "Araç Kiralama", parentId: "cmm1c5s4q000j10husxcryadk" },
  "avm": { name: "AVM & Alışveriş Merkezi", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "barlar": { name: "Barlar & Gece Hayatı", parentId: "cmm1c5s47000110hurokft6xf" },
  "dil-okulu": { name: "Dil Okulu", parentId: "cmm1c5s4k000b10huxb54fhhg" },
  "dis-sagligi": { name: "Diş Sağlığı", parentId: "cmm1c5s4d000310huxhyxtm0s" },
  "dovme-piercing": { name: "Dövme & Piercing", parentId: "cmm1c5s4f000510hus5r0euvg" },
  "dugun-organizasyon": { name: "Düğün & Organizasyon", parentId: "cmm1c5s4l000d10hugjjrhpy0" },
  "eczane": { name: "Eczane", parentId: "cmm1c5s4d000310huxhyxtm0s" },
  "egitim": { name: "Eğitim", parentId: null },
  "eglence-kultur": { name: "Eğlence & Kültür", parentId: null },
  "elektronik": { name: "Elektronik & Teknoloji", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "evcil-hayvan": { name: "Evcil Hayvan", parentId: null },
  "ev-mobilya": { name: "Ev & Mobilya", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "fast-food": { name: "Fast Food & Paket Servis", parentId: "cmm1c5s47000110hurokft6xf" },
  "giyim-moda": { name: "Giyim & Moda", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "guzellik-bakim": { name: "Güzellik & Bakım", parentId: null },
  "guzellik-merkezi": { name: "Güzellik Merkezi", parentId: "cmm1c5s4f000510hus5r0euvg" },
  "hastane": { name: "Hastane & Acil", parentId: "cmm1c5s4d000310huxhyxtm0s" },
  "hayvan-bakimevi": { name: "Hayvan Bakımevi", parentId: "cmm1c5s4p000h10hufyvberr8" },
  "hizmetler": { name: "Hizmetler", parentId: null },
  "hukuk": { name: "Hukuki Hizmetler", parentId: "cmm1c5s4i000910hu8q3k7xmc" },
  "kafe": { name: "Kafe", parentId: "cmm1c5s47000110hurokft6xf" },
  "kafeler": { name: "Kafeler", parentId: "cmm1c5s47000110hurokft6xf" },
  "kahve-cay": { name: "Kahve & Çay", parentId: "cmm1c5s47000110hurokft6xf" },
  "kitap-kirtasiye": { name: "Kitap & Kırtasiye", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "klinik-poliklinik": { name: "Klinik & Poliklinik", parentId: "cmm1c5s4d000310huxhyxtm0s" },
  "konaklama": { name: "Konaklama", parentId: null },
  "kuafor-berber": { name: "Kuaför & Berber", parentId: "cmm1c5s4f000510hus5r0euvg" },
  "kurs-dershane": { name: "Kurs & Dershane", parentId: "cmm1c5s4k000b10huxb54fhhg" },
  "market": { name: "Market", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "market-supermarket": { name: "Market & Süpermarket", parentId: "cmm1c5s4g000710hurgo9jgqv" },
  "muhasebe-finans": { name: "Muhasebe & Finans", parentId: "cmm1c5s4i000910hu8q3k7xmc" },
  "muzeler": { name: "Müze & Galeri", parentId: "cmm1c5s4l000d10hugjjrhpy0" },
  "muzik-sanat": { name: "Müzik & Sanat Kursları", parentId: "cmm1c5s4k000b10huxb54fhhg" },
  "nakliyat": { name: "Nakliyat & Taşımacılık", parentId: "cmm1c5s4i000910hu8q3k7xmc" },
  "okul": { name: "Okul & Lise", parentId: "cmm1c5s4k000b10huxb54fhhg" },
  "otel": { name: "Otel", parentId: "cmm1c5s4n000f10huk1igr6a6" },
  "oto-galeri": { name: "Oto Galeri", parentId: "cmm1c5s4q000j10husxcryadk" },
  "oto-servis": { name: "Oto Servis & Yedek Parça", parentId: "cmm1c5s4i000910hu8q3k7xmc" },
  "oyun-eglence": { name: "Oyun & Eğlence Merkezi", parentId: "cmm1c5s4l000d10hugjjrhpy0" },
  "pansiyon-hostel": { name: "Pansiyon & Hostel", parentId: "cmm1c5s4n000f10huk1igr6a6" },
  "parklar": { name: "Park & Doğa", parentId: "cmm1c5s4l000d10hugjjrhpy0" },
  "pastane-firin": { name: "Pastane & Fırın", parentId: "cmm1c5s47000110hurokft6xf" },
  "pet-shop": { name: "Pet Shop", parentId: "cmm1c5s4p000h10hufyvberr8" },
  "psikoloji-terapi": { name: "Psikoloji & Terapi", parentId: "cmm1c5s4d000310huxhyxtm0s" },
  "restoran": { name: "Restoran", parentId: "cmm1c5s47000110hurokft6xf" },
  "restoranlar": { name: "Restoranlar", parentId: "cmm1c5s47000110hurokft6xf" },
  "saglik-medikal": { name: "Sağlık & Medikal", parentId: null },
  "sinema": { name: "Sinema", parentId: "cmm1c5s4l000d10hugjjrhpy0" },
  "spa-masaj": { name: "Spa & Masaj", parentId: "cmm1c5s4f000510hus5r0euvg" },
  "spor-fitness": { name: "Spor & Fitness", parentId: "cmm1c5s4d000310huxhyxtm0s" },
  "tadilat-insaat": { name: "Tadilat & İnşaat", parentId: "cmm1c5s4i000910hu8q3k7xmc" },
  "taksi-servis": { name: "Taksi & Servis", parentId: "cmm1c5s4q000j10husxcryadk" },
  "temizlik": { name: "Temizlik Hizmetleri", parentId: "cmm1c5s4i000910hu8q3k7xmc" },
  "tirnak-studio": { name: "Tırnak Stüdyo", parentId: "cmm1c5s4f000510hus5r0euvg" },
  "ulasim": { name: "Ulaşım & Araç", parentId: null },
  "universite": { name: "Üniversite", parentId: "cmm1c5s4k000b10huxb54fhhg" },
  "veteriner": { name: "Veteriner", parentId: "cmm1c5s4p000h10hufyvberr8" },
  "yeme-icme": { name: "Yeme & İçme", parentId: null },
}

export const KATEGORI_SLUGS = ["alisveris","apart-kiralik","oto-kiralama","avm","barlar","dil-okulu","dis-sagligi","dovme-piercing","dugun-organizasyon","eczane","egitim","eglence-kultur","elektronik","evcil-hayvan","ev-mobilya","fast-food","giyim-moda","guzellik-bakim","guzellik-merkezi","hastane","hayvan-bakimevi","hizmetler","hukuk","kafe","kafeler","kahve-cay","kitap-kirtasiye","klinik-poliklinik","konaklama","kuafor-berber","kurs-dershane","market","market-supermarket","muhasebe-finans","muzeler","muzik-sanat","nakliyat","okul","otel","oto-galeri","oto-servis","oyun-eglence","pansiyon-hostel","parklar","pastane-firin","pet-shop","psikoloji-terapi","restoran","restoranlar","saglik-medikal","sinema","spa-masaj","spor-fitness","tadilat-insaat","taksi-servis","temizlik","tirnak-studio","ulasim","universite","veteriner","yeme-icme"]