import type { Business, Review, MuhtarUser } from '@/types'

export const MOCK_BUSINESSES: Business[] = [
  {
    id: '1',
    slug: 'kahve-dunyasi-moda',
    name: 'Kahve Dünyası Moda',
    category: 'Kafe',
    city: 'İstanbul',
    district: 'Kadıköy',
    address: 'Caferağa Mah. Moda Cad. No: 123',
    phone: '+90 216 123 45 67',
    website: 'www.kahvedunyasi.com',
    trustScore: {
      grade: 'A',
      score: 94,
      breakdown: { reviewDepth: 92, recencyTrend: 88, verifiedRatio: 96, engagement: 90 },
      trend: 'up',
    },
    trustStack: { sms: true, transaction: true, photo: true },
    hasGonulAlma: true,
    priceRange: '₺₺',
    features: ['wifi', 'priz', 'sessiz'],
    hours: '08:00 - 23:00',
    isOpen: true,
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=500&fit=crop',
    reviewCount: 1247,
    semanticMatch: 87,
    culturalTags: ['Porsiyon Doyurucu', 'Güleryüzlü Esnaf', 'Öğrenci Dostu'],
    badges: ['verified', 'neighborhood-favorite', 'gonul-alma'],
    aiSummary: {
      atmosphere: 'Sessiz, kitap okumaya uygun, bazen canlı müzik',
      price: 'Ortalama kahve 45-55 ₺, kahvaltı tabağı 120-150 ₺',
      bestTime: 'Hafta içi 09:00-11:00 sakin, hafta sonu 10:00\'dan önce gelin',
      highlights: ['Ev yapımı cheesecake', 'Özel kahve çekirdekleri', 'Sakin çalışma ortamı'],
    },
  },
  {
    id: '4',
    slug: 'bostanci-oto-servis-ahmet',
    name: 'Bostancı Oto Servis — Usta Ahmet',
    category: 'Oto Servis',
    city: 'İstanbul',
    district: 'Bostancı',
    address: 'Bostancı Mah. İstasyon Cad. No: 45',
    phone: '+90 216 456 78 90',
    trustScore: {
      grade: 'A',
      score: 96,
      breakdown: { reviewDepth: 94, recencyTrend: 92, verifiedRatio: 98, engagement: 88 },
      trend: 'stable',
    },
    trustStack: { sms: true, transaction: true, photo: true },
    hasGonulAlma: true,
    priceRange: '₺₺₺',
    features: ['diagnostic', 'expert', 'transparent-pricing'],
    hours: '08:00 - 19:00',
    isOpen: true,
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=500&fit=crop',
    reviewCount: 312,
    semanticMatch: 95,
    culturalTags: ['İşini Bilen Usta', 'Şeffaf Fiyat', 'Güvenilir'],
    badges: ['verified', 'expert-mechanic', 'transparent', 'gonul-alma'],
    aiSummary: {
      atmosphere: 'Profesyonel, şeffaf fiyatlandırma, 20+ yıllık tecrübe',
      price: 'Periyodik bakım 800-1200 ₺, işçilik saatlik 250 ₺',
      bestTime: 'Randevu ile çalışıyor, sabah erken saatler daha sakin',
      highlights: ['20 yıllık tecrübe', 'Şeffaf fiyat politikası', 'Orjinal yedek parça'],
    },
  },
  {
    id: '6',
    slug: 'kadikoy-matematik-kursu',
    name: 'Kadıköy Matematik Kursu',
    category: 'Eğitim',
    city: 'İstanbul',
    district: 'Kadıköy',
    address: 'Osmanağa Mah. Söğütlü Çeşme Cad. No: 12',
    phone: '+90 216 789 01 23',
    trustScore: {
      grade: 'B',
      score: 87,
      breakdown: { reviewDepth: 85, recencyTrend: 82, verifiedRatio: 90, engagement: 88 },
      trend: 'up',
    },
    trustStack: { sms: true, transaction: true, photo: false },
    priceRange: '₺₺₺',
    features: ['individual-attention', 'experienced-teachers'],
    hours: '09:00 - 21:00',
    isOpen: true,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=500&fit=crop',
    reviewCount: 156,
    semanticMatch: 88,
    culturalTags: ['Öğretmen İlgisi Yüksek', 'Veli Dostu', 'Disiplinli'],
    badges: ['verified', 'rising-star'],
    aiSummary: {
      atmosphere: 'Disiplinli, veli iletişimi güçlü, birebir ilgi',
      price: 'Aylık 2500-3500 ₺, özel ders 400 ₺/saat',
      bestTime: 'Hafta sonu grupları dolu, hafta içi tercih edin',
      highlights: ['Öğretmen ilgisi', 'Veli bilgilendirme sistemi', 'Düzenli deneme sınavları'],
    },
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    businessId: '1',
    businessName: 'Kahve Dünyası Moda',
    businessSlug: 'kahve-dunyasi-moda',
    userName: 'Ayşe Yılmaz',
    userHandle: '@ayseyilmaz',
    userImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    userIsMuhtar: true,
    userMuhtarNeighborhood: 'Moda',
    content: 'Harika bir çalışma ortamı! Sakin atmosferi ve bol prizleriyle laptopla çalışmak için ideal. WiFi hızlı ve kesintisiz. Flat white\'ları gerçekten çok lezzetli, özellikle hafta içi sabahları gelin.',
    rating: 5,
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300&h=200&fit=crop'],
    helpfulCount: 47,
    thankCount: 12,
    createdAt: '2 saat önce',
    shieldStatus: 'safe',
    sentiment: { type: 'positive', score: 95, irony: false },
    aiHighlights: ['Sakin atmosfer', 'WiFi hızlı', 'Flat white'],
  },
  {
    id: 'r2',
    businessId: '4',
    businessName: 'Bostancı Oto Servis — Usta Ahmet',
    businessSlug: 'bostanci-oto-servis-ahmet',
    userName: 'Can Yıldız',
    userHandle: '@canyildiz',
    userImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    userIsMuhtar: true,
    userMuhtarNeighborhood: 'Bostancı',
    userIsExpert: true,
    userExpertise: 'Oto Uzmanı',
    content: 'Usta Ahmet\'e 2018 model BMW\'mi götürdüm. Fiyatı önceden söyledi, işçilik harika. 3 saatte teslim etti, pazarlık yok, gizli ücret yok. Gerçekten nadir bulunan dürüst bir usta. Kesinlikle tavsiye.',
    rating: 5,
    photos: [],
    helpfulCount: 89,
    thankCount: 34,
    createdAt: '1 gün önce',
    shieldStatus: 'safe',
    sentiment: { type: 'positive', score: 98, irony: false },
    aiHighlights: ['Şeffaf fiyat', 'Pazarlık yok', 'Gizli ücret yok'],
  },
  {
    id: 'r3',
    businessId: '1',
    businessName: 'Kahve Dünyası Moda',
    businessSlug: 'kahve-dunyasi-moda',
    userName: 'Mehmet Kaya',
    userHandle: '@mehmetkaya42',
    content: 'Harika bir yer, zehirlenmek isteyen gitsin!',
    rating: 2,
    photos: [],
    helpfulCount: 23,
    thankCount: 5,
    createdAt: '5 saat önce',
    shieldStatus: 'safe',
    sentiment: { type: 'irony', score: 15, irony: true },
    ironyExplanation: '"Harika" ve "zehirlenmek" kelimeleri çelişiyor. Gerçek duygu: Olumsuz',
  },
  {
    id: 'r4',
    businessId: '4',
    businessName: 'Bostancı Oto Servis — Usta Ahmet',
    businessSlug: 'bostanci-oto-servis-ahmet',
    userName: 'Zeynep Demir',
    userHandle: '@zeynepdemir',
    userImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    content: 'Fiyat biraz yüksek ama değiyor. Arabanın düzgün tamir edilmesi en önemli şey, burada emin ellerdesiniz.',
    rating: 4,
    photos: [],
    helpfulCount: 18,
    thankCount: 8,
    createdAt: '2 gün önce',
    shieldStatus: 'warning',
    shieldReason: 'Aynı IP aralığından birden fazla yorum tespit edildi',
    sentiment: { type: 'positive', score: 85, irony: false },
  },
  {
    id: 'r5',
    businessId: '6',
    businessName: 'Kadıköy Matematik Kursu',
    businessSlug: 'kadikoy-matematik-kursu',
    userName: 'Fatma Öğretmen',
    userHandle: '@fatmaogretmen',
    userImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    userIsMuhtar: true,
    userMuhtarNeighborhood: 'Kadıköy',
    userIsExpert: true,
    userExpertise: 'Eğitim Uzmanı',
    content: 'Oğlum 2 ayda matematikten 45 netten 75 nete çıktı. Öğretmen ilgisi gerçekten farklı. Her hafta veli görüşmesi yapıyorlar, disiplinli bir sistemleri var. Kesinlikle tavsiye ediyorum.',
    rating: 5,
    photos: [],
    helpfulCount: 67,
    thankCount: 23,
    createdAt: '1 gün önce',
    shieldStatus: 'safe',
    sentiment: { type: 'positive', score: 94, irony: false },
    aiHighlights: ['Öğretmen ilgisi', 'Net artışı', 'Veli görüşmesi'],
  },
]

export const MOCK_MUHTARLAR: MuhtarUser[] = [
  {
    id: 'u2',
    name: 'Can Yıldız',
    handle: '@canyildiz',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    neighborhood: 'Bostancı',
    expertise: ['Oto Servis', 'Lastik', 'Yedek Parça'],
    reviewCount: 89,
    helpfulCount: 1567,
    followers: 445,
    rank: 1,
  },
  {
    id: 'u1',
    name: 'Ayşe Yılmaz',
    handle: '@ayseyilmaz',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    neighborhood: 'Moda',
    expertise: ['Kafe', 'Restoran'],
    reviewCount: 156,
    helpfulCount: 2341,
    followers: 892,
    rank: 2,
  },
  {
    id: 'u3',
    name: 'Fatma Öğretmen',
    handle: '@fatmaogretmen',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    neighborhood: 'Kadıköy',
    expertise: ['Eğitim', 'Kurs', 'Özel Ders'],
    reviewCount: 134,
    helpfulCount: 1234,
    followers: 678,
    rank: 3,
  },
]
